Av 2 general sign up page
The-furious/AVfrontend pull request #1
Opened 2024-02-09 09:45 UTC by gunjansamrit

2024-02-09 10:10 UTC, Sudhanshu10Sathawane requested changes

2024-02-09 10:10 UTC, Sudhanshu10Sathawane commented on avfrontend/src/App.js
> +      <header>
create a different header component

2024-02-09 10:10 UTC, Sudhanshu10Sathawane commented on avfrontend/src/App.js
> +      <div className="main">
Create this component as signup component

2024-02-09 10:10 UTC, Sudhanshu10Sathawane commented on avfrontend/src/App.js
> +      <footer>
For footer create component

2024-02-09 10:10 UTC, Sudhanshu10Sathawane commented on avfrontend/src/logins/DoctorLogin.jsx
> +    console.log(formData); // You can do further processing with the form data here
comment or remove log

2024-02-11 15:26 UTC, gunjansamrit commented on avfrontend/src/App.js
> +      <footer>
closse

2024-02-12 16:47 UTC, Sudhanshu10Sathawane approved these changes

2024-02-12 16:48 UTC, stsiyer approved these changes

2024-02-12 16:48 UTC, merged